spring.application.name=tomcat-jenkins
server.port=8085

# Thymeleaf default is src/main/resources/templates/ with .html suffix
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false